webapp/apps/files/sockets/__init__.py
from socket import SocketIO

from apps.files.sockets.views import disconnect, connect


def init_socketio_views(socketio: SocketIO) -> None:
    socketio.on_event('connect', connect)
    socketio.on_event('disconnect', disconnect)

webapp/apps/files/sockets/views.py
from uuid import uuid4

from flask import request
from flask_socketio import emit

from cache import cache


def connect():
    user_sid = request.cookies.get('userSID')
    if not user_sid:
        user_sid = str(uuid4())
        emit('setUserSID', user_sid)

    cache.delete(user_sid)
    cache.add(user_sid, request.sid)


def disconnect():
    user_sid = request.cookies['userSID']
    cache.delete(user_sid)

webapp/apps/files/views.py
import os
from io import BytesIO

from flask import Blueprint, send_file, render_template, jsonify, request
from marshmallow import ValidationError

from apps.files.schemas import FileUploadSchema
from apps.files.services.file_services import FilesService
from apps.files.services.ip_address_services import IpAddress
from apps.files.tasks import download_file, delete_replication_file
from config import Config


files_bp = Blueprint(
    'files_bp',
    __name__,
    template_folder='templates'
)


@files_bp.route('/', methods=['GET'])
def home():
    data = {
        'location': IpAddress(Config.AWS_INSTANCE_IP).get_location()
    }
    return render_template('home.html', **data)


@files_bp.route('/upload', methods=['POST'])
def upload():
    request_data = request.json
    schema = FileUploadSchema()
    try:
        validate_data = schema.load(request_data)
        download_file.delay(validate_data['url'], request.cookies['userSID'])
    except ValidationError as err:
        return jsonify(err.messages), 400
    return jsonify({'success': True})


@files_bp.route('/list-files')
def list_files():
    return jsonify(FilesService().list_files())


@files_bp.route('/test-download')
def test_download():
    data = BytesIO(os.urandom(500 * 1024))
    return send_file(data, mimetype='image/jpeg', as_attachment=True, download_name='test.jpg', max_age=0)


@files_bp.route('/download/<string:filename>')
def download(filename: str):
    file_stream = FilesService().get_file_stream_from_s3(filename)
    return send_file(file_stream, as_attachment=True, download_name=filename)


@files_bp.route('/delete/<string:filename>', methods=['DELETE'])
def delete(filename: str):
    try:
        FilesService().delete_file(filename)

        for bucket in FilesService.get_replica_buckets():
            delete_replication_file.delay(filename, request.cookies['userSID'], bucket)

    except ValidationError as err:
        return jsonify(err.messages), 400
    return jsonify(), 204

webapp/apps/files/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
      body,html {height:100%}
      .text-small {font-size:0.8rem}
      .top-border {border-top:1px dotted #000;margin-top:5px}
      .hide-div {display:none}
      .link-disabled {pointer-events:none;cursor:default;color:gray}
    </style>
  </head>
  <body>
    <div class="container h-100">
      <div class="row">
        <div class="col-12 text-center">
          <h1>GeoFile</h1>
          <p>{{ location.country }}, {{ location.region }}, {{ location.city }}, {{ location.ip }}</p>
        </div>
      </div>

      <div class="row">
        <div class="col-12 form-group">
          <label for="url-file-id">Paste the URL of the file</label>
          <input type="url" class="form-control" id="url-file-id" placeholder="Url">
        </div>
      </div>
      <input type="hidden" id="network-speed-id" value="">
      <input type="hidden" id="check-url-network-speed-id" value="{{ url_for('files_bp.test_download') }}">

      <div class="row">
        <div class="col-12" id="new-list-files-id"></div>
        <div class="col-12">
          <button id="get-list-files-id"
                  class="btn btn-primary btn-sm w-100"
                  data-list-url="{{ url_for('files_bp.list_files') }}"
                  style="margin:10px 0">Get List of Files</button>
        </div>
        <div class="col-12" id="old-list-files-id"></div>
      </div>

    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    <script>
      $(document).ready(function(){
          testDownloadSpeed();
          sendInputValue("#url-file-id", "{{ url_for('files_bp.upload') }}", "url");
          socketHandlers("{{ g.server_name }}");
          $("#get-list-files-id").click(function () {getListFiles(this)});
      });
    </script>
  </body>
</html>